"""
ConductorAI UI — Email Service
Handles sending emails for project reviews and notifications
"""

from __future__ import annotations

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional

import structlog
from pydantic import BaseModel

logger = structlog.get_logger()


class EmailConfig(BaseModel):
    """Email configuration settings"""
    smtp_server: str = "smtp.gmail.com"
    smtp_port: int = 587
    sender_email: str = "govindsona@gmail.com"
    sender_password: str = "ufrn osjr cpmk kwug"
    sender_name: str = "ConductorAI"
    use_tls: bool = True


class EmailMessage(BaseModel):
    """Email message structure"""
    recipient_email: str
    subject: str
    body_html: str
    body_text: Optional[str] = None


class EmailService:
    """Service for sending emails"""

    def __init__(self, config: Optional[EmailConfig] = None):
        """Initialize email service with configuration.
        
        Args:
            config: Email configuration. If None, uses environment variables.
        """
        self.config = config or EmailConfig()
        self.logger = logger

    async def send_project_review_email(
        self,
        recipient_email: str,
        recipient_name: str,
        project_name: str,
        project_id: str,
        github_repo: str,
        review_type: str = "pipeline",
        frontend_url: str = "http://localhost:3000",
    ) -> bool:
        """Send a project review request email.
        
        Args:
            recipient_email: Email address of reviewer
            recipient_name: Name of reviewer
            project_name: Name of the project
            project_id: ID of the project
            github_repo: GitHub repository URL/name
            review_type: Type of review (pipeline, readme, both)
            frontend_url: URL to the frontend application
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            review_items = []
            if review_type in ["pipeline", "both"]:
                review_items.append("pipeline.yaml")
            if review_type in ["readme", "both"]:
                review_items.append("README.md")

            review_items_html = "".join(
                f"<li>{item}</li>" for item in review_items
            )

            approval_url = f"{frontend_url}/projects/{project_id}/approve"

            html_body = f"""
            <html>
                <body style="font-family: Arial, sans-serif; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto;">
                        <h2 style="color: #2c3e50;">Project Review Request</h2>
                        
                        <p>Hi {recipient_name},</p>
                        
                        <p>A new project requires your review:</p>
                        
                        <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <p><strong>Project Name:</strong> {project_name}</p>
                            <p><strong>Project ID:</strong> {project_id}</p>
                            <p><strong>GitHub Repository:</strong> {github_repo}</p>
                        </div>
                        
                        <h3>Items for Review:</h3>
                        <ul>
                            {review_items_html}
                        </ul>
                        
                        <p>These files have been automatically generated by ConductorAI and are ready for your review.</p>
                        
                        <div style="margin: 30px 0;">
                            <a href="{approval_url}" 
                               style="background-color: #27ae60; color: white; padding: 12px 30px; 
                                      text-decoration: none; border-radius: 5px; display: inline-block;">
                                Review & Approve in ConductorAI
                            </a>
                        </div>
                        
                        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
                        
                        <p style="font-size: 12px; color: #999;">
                            This is an automated message from ConductorAI. 
                            Please do not reply to this email.
                        </p>
                    </div>
                </body>
            </html>
            """

            text_body = f"""
Project Review Request

Hi {recipient_name},

A new project requires your review:

Project Name: {project_name}
Project ID: {project_id}
GitHub Repository: {github_repo}

Items for Review:
{chr(10).join(f"- {item}" for item in review_items)}

These files have been automatically generated by ConductorAI and are ready for your review.

Review & Approve: {approval_url}

---
This is an automated message from ConductorAI. Please do not reply to this email.
            """

            message = EmailMessage(
                recipient_email=recipient_email,
                subject=f"Project Review Request: {project_name}",
                body_html=html_body,
                body_text=text_body,
            )

            return await self.send(message)

        except Exception as e:
            self.logger.error(
                "send_project_review_email_failed",
                error=str(e),
                recipient_email=recipient_email,
                project_id=project_id,
            )
            return False

    async def send_approval_confirmation_email(
        self,
        recipient_email: str,
        recipient_name: str,
        project_name: str,
        project_id: str,
        approved_by: str,
    ) -> bool:
        """Send approval confirmation email.
        
        Args:
            recipient_email: Email address to send to
            recipient_name: Name of recipient
            project_name: Name of the project
            project_id: ID of the project
            approved_by: Name of person who approved
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            html_body = f"""
            <html>
                <body style="font-family: Arial, sans-serif; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto;">
                        <h2 style="color: #27ae60;">✓ Project Approved</h2>
                        
                        <p>Hi {recipient_name},</p>
                        
                        <p>The project has been reviewed and approved:</p>
                        
                        <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <p><strong>Project Name:</strong> {project_name}</p>
                            <p><strong>Project ID:</strong> {project_id}</p>
                            <p><strong>Approved By:</strong> {approved_by}</p>
                        </div>
                        
                        <p>The pipeline is now ready for execution. Team members have been notified.</p>
                        
                        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
                        
                        <p style="font-size: 12px; color: #999;">
                            This is an automated message from ConductorAI.
                        </p>
                    </div>
                </body>
            </html>
            """

            text_body = f"""
Project Approved

Hi {recipient_name},

The project has been reviewed and approved:

Project Name: {project_name}
Project ID: {project_id}
Approved By: {approved_by}

The pipeline is now ready for execution. Team members have been notified.

---
This is an automated message from ConductorAI.
            """

            message = EmailMessage(
                recipient_email=recipient_email,
                subject=f"Project Approved: {project_name}",
                body_html=html_body,
                body_text=text_body,
            )

            return await self.send(message)

        except Exception as e:
            self.logger.error(
                "send_approval_confirmation_email_failed",
                error=str(e),
                recipient_email=recipient_email,
                project_id=project_id,
            )
            return False

    async def send(self, message: EmailMessage) -> bool:
        """Send an email message.
        
        Args:
            message: EmailMessage object with recipient, subject, and body
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            if not self.config.sender_email or not self.config.sender_password:
                self.logger.warning(
                    "email_service_not_configured",
                    detail="sender_email or sender_password not configured",
                )
                return False

            # Create email message
            msg = MIMEMultipart("alternative")
            msg["Subject"] = message.subject
            msg["From"] = f"{self.config.sender_name} <{self.config.sender_email}>"
            msg["To"] = message.recipient_email

            # Attach text and HTML parts
            if message.body_text:
                msg.attach(MIMEText(message.body_text, "plain"))
            msg.attach(MIMEText(message.body_html, "html"))

            # Send email
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls()
                server.login(self.config.sender_email, self.config.sender_password)
                server.sendmail(
                    self.config.sender_email,
                    message.recipient_email,
                    msg.as_string(),
                )

            self.logger.info(
                "email_sent_successfully",
                recipient=message.recipient_email,
                subject=message.subject,
            )
            return True

        except Exception as e:
            self.logger.error(
                "email_send_failed",
                error=str(e),
                recipient=message.recipient_email,
                subject=message.subject,
            )
            return False

