apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductorai.fullname" . }}
  labels:
    {{- include "conductorai.labels" . | nindent 4 }}
type: Opaque
data:
  CONDUCTOR_LLM__API_KEY: {{ .Values.llm.apiKey | b64enc | quote }}
  CONDUCTOR_REDIS__PASSWORD: {{ .Values.redis.password | b64enc | quote }}
